const types = @import("types.zig");

pub fn opcode_info(opcode: u8) types.OpcodeInfo {
    return switch (opcode) {
        0x69 => types.OpcodeInfo{ .instruction = .adc, .mode = .immediate },
        0x65 => types.OpcodeInfo{ .instruction = .adc, .mode = .zero_page },
        0x75 => types.OpcodeInfo{ .instruction = .adc, .mode = .zero_page_x },
        0x6D => types.OpcodeInfo{ .instruction = .adc, .mode = .absolute },
        0x7D => types.OpcodeInfo{ .instruction = .adc, .mode = .absolute_x },
        0x79 => types.OpcodeInfo{ .instruction = .adc, .mode = .absolute_y },
        0x61 => types.OpcodeInfo{ .instruction = .adc, .mode = .indirect_x },
        0x71 => types.OpcodeInfo{ .instruction = .adc, .mode = .indirect_y },

        0x29 => types.OpcodeInfo{ .instruction = .and_, .mode = .immediate },
        0x25 => types.OpcodeInfo{ .instruction = .and_, .mode = .zero_page },
        0x35 => types.OpcodeInfo{ .instruction = .and_, .mode = .zero_page_x },
        0x2D => types.OpcodeInfo{ .instruction = .and_, .mode = .absolute },
        0x3D => types.OpcodeInfo{ .instruction = .and_, .mode = .absolute_x },
        0x39 => types.OpcodeInfo{ .instruction = .and_, .mode = .absolute_y },
        0x21 => types.OpcodeInfo{ .instruction = .and_, .mode = .indirect_x },
        0x31 => types.OpcodeInfo{ .instruction = .and_, .mode = .indirect_y },

        0x0A => types.OpcodeInfo{ .instruction = .asl, .mode = .accumulator },
        0x06 => types.OpcodeInfo{ .instruction = .asl, .mode = .zero_page },
        0x16 => types.OpcodeInfo{ .instruction = .asl, .mode = .zero_page_x },
        0x0E => types.OpcodeInfo{ .instruction = .asl, .mode = .absolute },
        0x1E => types.OpcodeInfo{ .instruction = .asl, .mode = .absolute_x },

        0x90 => types.OpcodeInfo{ .instruction = .bcc, .mode = .relative },
        0xB0 => types.OpcodeInfo{ .instruction = .bcs, .mode = .relative },
        0xF0 => types.OpcodeInfo{ .instruction = .beq, .mode = .relative },

        0x24 => types.OpcodeInfo{ .instruction = .bit, .mode = .zero_page },
        0x2C => types.OpcodeInfo{ .instruction = .bit, .mode = .absolute },

        0x30 => types.OpcodeInfo{ .instruction = .bmi, .mode = .relative },
        0xD0 => types.OpcodeInfo{ .instruction = .bne, .mode = .relative },
        0x10 => types.OpcodeInfo{ .instruction = .bpl, .mode = .relative },

        0x00 => types.OpcodeInfo{ .instruction = .brk, .mode = .implied },

        0x50 => types.OpcodeInfo{ .instruction = .bvc, .mode = .relative },
        0x70 => types.OpcodeInfo{ .instruction = .bvs, .mode = .relative },

        0x18 => types.OpcodeInfo{ .instruction = .clc, .mode = .implied },
        0xD8 => types.OpcodeInfo{ .instruction = .cld, .mode = .implied },
        0x58 => types.OpcodeInfo{ .instruction = .cli, .mode = .implied },
        0xB8 => types.OpcodeInfo{ .instruction = .clv, .mode = .implied },

        0xC9 => types.OpcodeInfo{ .instruction = .cmp, .mode = .immediate },
        0xC5 => types.OpcodeInfo{ .instruction = .cmp, .mode = .zero_page },
        0xD5 => types.OpcodeInfo{ .instruction = .cmp, .mode = .zero_page_x },
        0xCD => types.OpcodeInfo{ .instruction = .cmp, .mode = .absolute },
        0xDD => types.OpcodeInfo{ .instruction = .cmp, .mode = .absolute_x },
        0xD9 => types.OpcodeInfo{ .instruction = .cmp, .mode = .absolute_y },
        0xC1 => types.OpcodeInfo{ .instruction = .cmp, .mode = .indirect_x },
        0xD1 => types.OpcodeInfo{ .instruction = .cmp, .mode = .indirect_y },

        0xE0 => types.OpcodeInfo{ .instruction = .cpx, .mode = .immediate },
        0xE4 => types.OpcodeInfo{ .instruction = .cpx, .mode = .zero_page },
        0xEC => types.OpcodeInfo{ .instruction = .cpx, .mode = .absolute },

        0xC0 => types.OpcodeInfo{ .instruction = .cpy, .mode = .immediate },
        0xC4 => types.OpcodeInfo{ .instruction = .cpy, .mode = .zero_page },
        0xCC => types.OpcodeInfo{ .instruction = .cpy, .mode = .absolute },

        0xC6 => types.OpcodeInfo{ .instruction = .dec, .mode = .zero_page },
        0xD6 => types.OpcodeInfo{ .instruction = .dec, .mode = .zero_page_x },
        0xCE => types.OpcodeInfo{ .instruction = .dec, .mode = .absolute },
        0xDE => types.OpcodeInfo{ .instruction = .dec, .mode = .absolute_x },

        0xCA => types.OpcodeInfo{ .instruction = .dex, .mode = .implied },
        0x88 => types.OpcodeInfo{ .instruction = .dey, .mode = .implied },

        0x49 => types.OpcodeInfo{ .instruction = .eor, .mode = .immediate },
        0x45 => types.OpcodeInfo{ .instruction = .eor, .mode = .zero_page },
        0x55 => types.OpcodeInfo{ .instruction = .eor, .mode = .zero_page_x },
        0x4D => types.OpcodeInfo{ .instruction = .eor, .mode = .absolute },
        0x5D => types.OpcodeInfo{ .instruction = .eor, .mode = .absolute_x },
        0x59 => types.OpcodeInfo{ .instruction = .eor, .mode = .absolute_y },
        0x41 => types.OpcodeInfo{ .instruction = .eor, .mode = .indirect_x },
        0x51 => types.OpcodeInfo{ .instruction = .eor, .mode = .indirect_y },

        0xE6 => types.OpcodeInfo{ .instruction = .inc, .mode = .zero_page },
        0xF6 => types.OpcodeInfo{ .instruction = .inc, .mode = .zero_page_x },
        0xEE => types.OpcodeInfo{ .instruction = .inc, .mode = .absolute },
        0xFE => types.OpcodeInfo{ .instruction = .inc, .mode = .absolute_x },
        0xE8 => types.OpcodeInfo{ .instruction = .inx, .mode = .implied },
        0xC8 => types.OpcodeInfo{ .instruction = .iny, .mode = .implied },

        0x4C => types.OpcodeInfo{ .instruction = .jmp, .mode = .absolute },
        0x6C => types.OpcodeInfo{ .instruction = .jmp, .mode = .indirect },
        0x20 => types.OpcodeInfo{ .instruction = .jsr, .mode = .absolute },

        0xA9 => types.OpcodeInfo{ .instruction = .lda, .mode = .immediate },
        0xA5 => types.OpcodeInfo{ .instruction = .lda, .mode = .zero_page },
        0xB5 => types.OpcodeInfo{ .instruction = .lda, .mode = .zero_page_x },
        0xAD => types.OpcodeInfo{ .instruction = .lda, .mode = .absolute },
        0xBD => types.OpcodeInfo{ .instruction = .lda, .mode = .absolute_x },
        0xB9 => types.OpcodeInfo{ .instruction = .lda, .mode = .absolute_y },
        0xA1 => types.OpcodeInfo{ .instruction = .lda, .mode = .indirect_x },
        0xB1 => types.OpcodeInfo{ .instruction = .lda, .mode = .indirect_y },

        0xA2 => types.OpcodeInfo{ .instruction = .ldx, .mode = .immediate },
        0xA6 => types.OpcodeInfo{ .instruction = .ldx, .mode = .zero_page },
        0xB6 => types.OpcodeInfo{ .instruction = .ldx, .mode = .zero_page_y },
        0xAE => types.OpcodeInfo{ .instruction = .ldx, .mode = .absolute },
        0xBE => types.OpcodeInfo{ .instruction = .ldx, .mode = .absolute_y },

        0xA0 => types.OpcodeInfo{ .instruction = .ldy, .mode = .immediate },
        0xA4 => types.OpcodeInfo{ .instruction = .ldy, .mode = .zero_page },
        0xB4 => types.OpcodeInfo{ .instruction = .ldy, .mode = .zero_page_x },
        0xAC => types.OpcodeInfo{ .instruction = .ldy, .mode = .absolute },
        0xBC => types.OpcodeInfo{ .instruction = .ldy, .mode = .absolute_x },

        0x4A => types.OpcodeInfo{ .instruction = .lsr, .mode = .accumulator },
        0x46 => types.OpcodeInfo{ .instruction = .lsr, .mode = .zero_page },
        0x56 => types.OpcodeInfo{ .instruction = .lsr, .mode = .zero_page_x },
        0x4E => types.OpcodeInfo{ .instruction = .lsr, .mode = .absolute },
        0x5E => types.OpcodeInfo{ .instruction = .lsr, .mode = .absolute_x },

        0xEA => types.OpcodeInfo{ .instruction = .nop, .mode = .implied },

        0x09 => types.OpcodeInfo{ .instruction = .ora, .mode = .immediate },
        0x05 => types.OpcodeInfo{ .instruction = .ora, .mode = .zero_page },
        0x15 => types.OpcodeInfo{ .instruction = .ora, .mode = .zero_page_x },
        0x0D => types.OpcodeInfo{ .instruction = .ora, .mode = .absolute },
        0x1D => types.OpcodeInfo{ .instruction = .ora, .mode = .absolute_x },
        0x19 => types.OpcodeInfo{ .instruction = .ora, .mode = .absolute_y },
        0x01 => types.OpcodeInfo{ .instruction = .ora, .mode = .indirect_x },
        0x11 => types.OpcodeInfo{ .instruction = .ora, .mode = .indirect_y },

        0x48 => types.OpcodeInfo{ .instruction = .pha, .mode = .implied },
        0x08 => types.OpcodeInfo{ .instruction = .php, .mode = .implied },
        0x68 => types.OpcodeInfo{ .instruction = .pla, .mode = .implied },
        0x28 => types.OpcodeInfo{ .instruction = .plp, .mode = .implied },

        0x2A => types.OpcodeInfo{ .instruction = .rol, .mode = .accumulator },
        0x26 => types.OpcodeInfo{ .instruction = .rol, .mode = .zero_page },
        0x36 => types.OpcodeInfo{ .instruction = .rol, .mode = .zero_page_x },
        0x2E => types.OpcodeInfo{ .instruction = .rol, .mode = .absolute },
        0x3E => types.OpcodeInfo{ .instruction = .rol, .mode = .absolute_x },
        0x6A => types.OpcodeInfo{ .instruction = .ror, .mode = .accumulator },
        0x66 => types.OpcodeInfo{ .instruction = .ror, .mode = .zero_page },
        0x76 => types.OpcodeInfo{ .instruction = .ror, .mode = .zero_page_x },
        0x6E => types.OpcodeInfo{ .instruction = .ror, .mode = .absolute },
        0x7E => types.OpcodeInfo{ .instruction = .ror, .mode = .absolute_x },

        0x40 => types.OpcodeInfo{ .instruction = .rti, .mode = .implied },
        0x60 => types.OpcodeInfo{ .instruction = .rts, .mode = .implied },

        0xE9 => types.OpcodeInfo{ .instruction = .sbc, .mode = .immediate },
        0xE5 => types.OpcodeInfo{ .instruction = .sbc, .mode = .zero_page },
        0xF5 => types.OpcodeInfo{ .instruction = .sbc, .mode = .zero_page_x },
        0xED => types.OpcodeInfo{ .instruction = .sbc, .mode = .absolute },
        0xFD => types.OpcodeInfo{ .instruction = .sbc, .mode = .absolute_x },
        0xF9 => types.OpcodeInfo{ .instruction = .sbc, .mode = .absolute_y },
        0xE1 => types.OpcodeInfo{ .instruction = .sbc, .mode = .indirect_x },
        0xF1 => types.OpcodeInfo{ .instruction = .sbc, .mode = .indirect_y },

        0x38 => types.OpcodeInfo{ .instruction = .sec, .mode = .implied },
        0xF8 => types.OpcodeInfo{ .instruction = .sed, .mode = .implied },
        0x78 => types.OpcodeInfo{ .instruction = .sei, .mode = .implied },

        0x85 => types.OpcodeInfo{ .instruction = .sta, .mode = .zero_page },
        0x95 => types.OpcodeInfo{ .instruction = .sta, .mode = .zero_page_x },
        0x8D => types.OpcodeInfo{ .instruction = .sta, .mode = .absolute },
        0x9D => types.OpcodeInfo{ .instruction = .sta, .mode = .absolute_x },
        0x99 => types.OpcodeInfo{ .instruction = .sta, .mode = .absolute_y },
        0x81 => types.OpcodeInfo{ .instruction = .sta, .mode = .indirect_x },
        0x91 => types.OpcodeInfo{ .instruction = .sta, .mode = .indirect_y },

        0x86 => types.OpcodeInfo{ .instruction = .stx, .mode = .zero_page },
        0x96 => types.OpcodeInfo{ .instruction = .stx, .mode = .zero_page_y },
        0x8E => types.OpcodeInfo{ .instruction = .stx, .mode = .absolute },
        0x84 => types.OpcodeInfo{ .instruction = .sty, .mode = .zero_page },
        0x94 => types.OpcodeInfo{ .instruction = .sty, .mode = .zero_page_x },
        0x8C => types.OpcodeInfo{ .instruction = .sty, .mode = .absolute },

        0xAA => types.OpcodeInfo{ .instruction = .tax, .mode = .implied },
        0xA8 => types.OpcodeInfo{ .instruction = .tay, .mode = .implied },
        0xBA => types.OpcodeInfo{ .instruction = .tsx, .mode = .implied },
        0x8A => types.OpcodeInfo{ .instruction = .txa, .mode = .implied },
        0x9A => types.OpcodeInfo{ .instruction = .txs, .mode = .implied },
        0x98 => types.OpcodeInfo{ .instruction = .tya, .mode = .implied },

        0x0C => types.OpcodeInfo{ .instruction = .dop, .mode = .absolute },
        0x1C => types.OpcodeInfo{ .instruction = .dop, .mode = .absolute_x },
        0x3C => types.OpcodeInfo{ .instruction = .dop, .mode = .absolute_x },
        0x5C => types.OpcodeInfo{ .instruction = .dop, .mode = .absolute_x },
        0x7C => types.OpcodeInfo{ .instruction = .dop, .mode = .absolute_x },
        0xDC => types.OpcodeInfo{ .instruction = .dop, .mode = .absolute_x },
        0xFC => types.OpcodeInfo{ .instruction = .dop, .mode = .absolute_x },

        0x04 => types.OpcodeInfo{ .instruction = .dop, .mode = .zero_page },
        0x14 => types.OpcodeInfo{ .instruction = .dop, .mode = .zero_page_x },
        0x34 => types.OpcodeInfo{ .instruction = .dop, .mode = .zero_page_x },
        0x44 => types.OpcodeInfo{ .instruction = .dop, .mode = .zero_page },
        0x54 => types.OpcodeInfo{ .instruction = .dop, .mode = .zero_page_x },
        0x64 => types.OpcodeInfo{ .instruction = .dop, .mode = .zero_page },
        0x74 => types.OpcodeInfo{ .instruction = .dop, .mode = .zero_page_x },
        0x80 => types.OpcodeInfo{ .instruction = .dop, .mode = .immediate },
        0x82 => types.OpcodeInfo{ .instruction = .dop, .mode = .immediate },
        0x89 => types.OpcodeInfo{ .instruction = .dop, .mode = .immediate },
        0xC2 => types.OpcodeInfo{ .instruction = .dop, .mode = .immediate },
        0xD4 => types.OpcodeInfo{ .instruction = .dop, .mode = .zero_page_x },
        0xE2 => types.OpcodeInfo{ .instruction = .dop, .mode = .immediate },
        0xF4 => types.OpcodeInfo{ .instruction = .dop, .mode = .zero_page_x },

        0x1A => types.OpcodeInfo{ .instruction = .dop, .mode = .implied },
        0x3A => types.OpcodeInfo{ .instruction = .dop, .mode = .implied },
        0x5A => types.OpcodeInfo{ .instruction = .dop, .mode = .implied },
        0x7A => types.OpcodeInfo{ .instruction = .dop, .mode = .implied },
        0xDA => types.OpcodeInfo{ .instruction = .dop, .mode = .implied },
        0xFA => types.OpcodeInfo{ .instruction = .dop, .mode = .implied },

        0xA7 => types.OpcodeInfo{ .instruction = .lax, .mode = .zero_page },
        0xB7 => types.OpcodeInfo{ .instruction = .lax, .mode = .zero_page_y },
        0xAF => types.OpcodeInfo{ .instruction = .lax, .mode = .absolute },
        0xBF => types.OpcodeInfo{ .instruction = .lax, .mode = .absolute_y },
        0xA3 => types.OpcodeInfo{ .instruction = .lax, .mode = .indirect_x },
        0xB3 => types.OpcodeInfo{ .instruction = .lax, .mode = .indirect_y },

        0x87 => types.OpcodeInfo{ .instruction = .sax, .mode = .zero_page },
        0x97 => types.OpcodeInfo{ .instruction = .sax, .mode = .zero_page_y },
        0x83 => types.OpcodeInfo{ .instruction = .sax, .mode = .indirect_x },
        0x8F => types.OpcodeInfo{ .instruction = .sax, .mode = .absolute },

        0xEB => types.OpcodeInfo{ .instruction = .sbc, .mode = .immediate },

        else => unreachable,
    };
}
